import { readdir, stat, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const SITE_URL = "https://www.trtdose.com";
const ROOT_DIR = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const SITEMAP_PATH = path.join(ROOT_DIR, "sitemap.xml");

const formatDate = (date) => date.toISOString().slice(0, 10);

const getPriority = (route) => {
  if (route === "/") return "1.0";
  if (route.includes("how-it-works")) return "0.8";
  if (route.includes("disclaimer")) return "0.6";
  return "0.7";
};

const escapeXml = (value) => value
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;")
  .replaceAll("'", "&apos;");

const getHtmlPages = async () => {
  const entries = await readdir(ROOT_DIR, { withFileTypes: true });
  const htmlFiles = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".html"))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));

  const pages = [];

  for (const fileName of htmlFiles) {
    const filePath = path.join(ROOT_DIR, fileName);
    const fileStats = await stat(filePath);
    const lastmod = formatDate(fileStats.mtime);

    // Homepage is exposed both as "/" and "/index.html" because some static hosts
    // serve both. The canonical tag still points to the preferred "/" URL.
    if (fileName === "index.html") {
      pages.push({ route: "/", lastmod });
    }

    pages.push({ route: `/${fileName}`, lastmod });
  }

  return pages;
};

const routeWeight = (route) => {
  if (route === "/") return 0;
  if (route === "/index.html") return 1;
  return 2;
};

const buildSitemap = (pages) => {
  const urls = [...pages].sort((a, b) => {
    const weightDiff = routeWeight(a.route) - routeWeight(b.route);
    return weightDiff || a.route.localeCompare(b.route);
  }).map((page) => `  <url>
    <loc>${escapeXml(`${SITE_URL}${page.route}`)}</loc>
    <lastmod>${page.lastmod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${getPriority(page.route)}</priority>
  </url>`).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs. Add future static pages as root .html files and rerun the script. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
};

const pages = await getHtmlPages();
await writeFile(SITEMAP_PATH, buildSitemap(pages), "utf8");
